development:
  host: '127.0.0.1'
  port: 9042
  keyspace: hickory_development
  max_retries: 3
  retry_delay: 0.5
  newrelic: false

test:
  host: '127.0.0.1'
  port: 9042
  keyspace: hickory_test
  max_retries: 3
  retry_delay: 0.5
  newrelic: false

production:
  hosts:
    - 'cass1.hickory.biz'
    - 'cass2.hickory.biz'
    - 'cass3.hickory.biz'
  port: 9042
  keyspace: hickory
  username: <%= Figaro.env.cass_username! %>
  password: <%= Figaro.env.cass_password! %>
  max_retries: 3
  retry_delay: 0.5
  newrelic: true
  replication:
    class: SimpleStrategy
    replication_factor: 1
# replication:
#   class: NetworkTopologyStrategy
#   datacenter1: 3
#   datacenter2: 2
# durable_writes: false
